train:
	python3 ./run_dqn.py breakout dqn brick_hunter --memory_capacity 100000 --memory_capacity
quick_train:
	python ./run_dqn.py breakout dqn brick_hunter --memory_capacity 100000 --epochs=10 --random_exploration_length=500 --epoch_length=500
quick_watch:
	python ./run_dqn.py breakout dqn brick_hunter_example  --watch --memory_capacity 100000 --epochs=10 --random_exploration_length=500 --epoch_length=500